### ISSUE TITLE
will update this generater to generate [component,router,service] like yeoman's angular-generator?

### ISSUE THREAD

**Issue by axetroy** [chrisdwheatley/generator-angular2#42]
i hope it will similar to yeoman official generator [generator-angular];
let us build a angular2 app easy.
provide a complete develop environment to build a app.
in short,many people will happy to see this;
rise up and like!

**Comment by swirlycheetah** [comment]
I'm not entirely sure on the future quite yet, with the announcement of [angular-cli](https://github.com/angular/angular-cli) at AngularConnect there may not be a need for a Yeoman generator which achieves practically the same thing. I'll be keeping an eye out on angular-cli to see how it progresses.
