### ISSUE TITLE
Update readme to mention this generator uses beta instead of alpha release

### ISSUE THREAD

**Issue by harryi3t** [chrisdwheatley/generator-angular2#47]
The readme says

```
A Yeoman Generator to aid in bootstrapping an Angular2 application using the very latest 
  Angular2 alpha release.
```

But https://github.com/swirlycheetah/generator-angular2/issues/41#issuecomment-178449924 says that this is using beta version of angular.

Just to avoid the confusion, could you update the readme saying that now this generator uses angular beta

**Comment by albertpak** [comment]
I've added a change in my PR - https://github.com/swirlycheetah/generator-angular2/pull/51  - @swirlycheetah lmk if i should break it up into separate PRs

**Comment by vuxor** [comment]
Merged.
