### ISSUE TITLE
Typescript errors on newly created project

### ISSUE THREAD

**Issue by smatthews1999** [chrisdwheatley/generator-angular2#54]
![image](https://cloud.githubusercontent.com/assets/562964/18294797/e60d5f0a-7469-11e6-9c75-8b73a63c4220.png)
![image](https://cloud.githubusercontent.com/assets/562964/18294800/f65970ba-7469-11e6-9d39-a2ade097f813.png)

I'm new to typescript.  No idea.

**Comment by ryuhhnn** [comment]
Looks like you're using atom. Have you tried downloading the TypeScript language into atom? Code looks good but it looks like it's trying to interpret the file as JavaScript.

**Comment by smatthews1999** [comment]
I was using VS Code in fact.  Still learning TS...but I have found that these problems tend to resolve themselves.
